# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request!
  We have detected this is the first time for you to contribute
  to *dMRIPrep*.
  Please check out our [contributing guidelines](https://github.com/nipreps/dmriprep/blob/master/CONTRIBUTING.rst).

  We invite you to list yourself as a *dMRIPrep* contributor, so if your name
  is not already mentioned, please modify the
  [``.zenodo.json``](https://github.com/nipreps/dmriprep/blob/master/.zenodo.json)
  file and insert yor data last in the ``contributors`` list. Example:

  ```JSON
  {
     "name": "Contributor, New dMRIPrep",
     "affiliation": "Department of dMRI prep'ing, Open Science Made-Up University",
     "orcid": "<your id>",
     "type": "Researcher"
  }
  ```


  Of course, if you want to opt-out this time there is no
  problem at all with adding your name later.
  You will be always welcome to add it in the future whenever
  you feel it should be listed.
