#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: dmriprep-docker /input_dir /output_dir"
    exit
fi

if [ -z "$2" ]; then
    echo "usage: dmriprep-docker /input_dir /output_dir"
    exit
fi

if [ -z "$3" ]; then
    docker run --rm -ti -v "$1":/inputs -v "$2":/outputs dmriprep:prod dmriprep /inputs /outputs
else
    inputDir=$1
    outputDir=$2

    shift 2

    docker run --rm -ti -v "$inputDir":/inputs -v "$outputDir":/outputs dmriprep:prod dmriprep /inputs /outputs --participant-label "$@"
fi
